/******************************************************************************
filename    stdafx.c
author      Matthew Picioccio (autogenerated)

Brief Description:
This file includes just the standard includes.
GAM100Project.pch will be the pre-compiled header
stdafx.obj will contain the pre-compiled type information.

******************************************************************************/
#include "stdafx.h"

/* NOTE: there must be at least one empty line after the #include, or the compiler gets confused */